# This file runs the t2wml Web application through Docker, and exposes it on port 8080.
#
# t2wml-web (this repo, use the develop branch)
#
# To run, just run `docker-compose up`

version: '3.7'

services:
    t2wml-backend:
        build:
          context: .
          dockerfile: Dockerfile-backend
        expose:
            - "13000"
        ports:
            - "13000:13000"
        container_name: t2wml-backend

    t2wml-web:
        build: .
        expose:
            - "80"
        ports:
            - "8080:80"
        container_name: t2wml-web
