export const DEFAULT_TAGS = {
    'FactorClass': [
        "AffinityGroups",
        "AgriculturalIndustry",
        "AirPollutionLevels",
        "AirTransportation",
        "AlternativeEnergyIndustry",
        "ArmedForces",
        "AveragePopulationAge",
        "BasicNeeds",
        "BusinessAndIndustryInfluence",
        "CentralOrLocalGovernment",
        "CivilMilitaryOperations",
        "CommunicationRestrictions",
        "Consumption",
        "Corruption",
        "CriminalActivities",
        "DefenseInformation",
        "Distribution",
        "Economic",
        "EconomicProduction-GDP",
        "EconomicSanctions",
        "EconomicServicesProduction",
        "EducationAvailability",
        "EmergencyFacilityAvailability",
        "EmploymentLevel",
        "EnvironmentConditions",
        "EthnicTensions",
        "EthnicTensionsInGovt",
        "ExtraJudicialActivity",
        "FoodAndNutritionLevel",
        "ForeignArmsTrade",
        "ForeignInvestment",
        "FreedomOfExpression",
        "FreedomOfReligiousExpression",
        "GovernmentAbilityToAddressBasicNeeds",
        "GovernmentBuildings",
        "GovernmentEffectiveness",
        "GovernmentPolicyActivity",
        "GovernmentStability",
        "GovernmentTransparency",
        "GroundTransportation",
        "Habitability",
        "HealthcareAvailability",
        "HumanTrafficking",
        "IllicitTrade",
        "IncomeInequality",
        "IndustrialEmploymentRate",
        "Industry",
        "Informal",
        "Information",
        "Infrastructure",
        "Institutions",
        "InsurgentsOrSeparatistsActivities",
        "InternallyDisplacedPersons",
        "InternalSecurity",
        "InternationalTrade",
        "InternetServiceAvailability",
        "JudicialActivity",
        "Leadership",
        "LegislativeActivity",
        "LogisticsReadiness",
        "ManufacturingIndustry",
        "MassCommunication",
        "Military",
        "MilitaryActivity",
        "MilitaryAirActivity",
        "MilitaryAirCapability",
        "MilitaryAirReadiness",
        "MilitaryC2Capability",
        "MilitaryCBRNECapability",
        "MilitaryCBRNEReadiness",
        "MilitaryConflict",
        "MilitaryCyberActivity",
        "MilitaryCyberCapability",
        "MilitaryCyberReadiness",
        "MilitaryDeployment",
        "MilitaryGroundActivity",
        "MilitaryGroundCapability",
        "MilitaryGroundReadiness",
        "Military-IndustrialBase",
        "MilitaryInfluenceOnGovernment",
        "MilitaryInformationEnvironmentActivity",
        "MilitaryIntelligenceActivity",
        "MilitaryIntelligenceCapability",
        "MilitaryIntelligenceReadiness",
        "MilitaryLawEnforcement",
        "MilitaryLogisticsCapability",
        "MilitaryNavalActivity",
        "MilitaryNavalCapability",
        "MilitaryNavalReadiness",
        "MilitaryReadiness",
        "MilitaryRecruitment",
        "MilitaryResearchAndDevelopment",
        "MilitarySpaceActivity",
        "MilitarySpaceCapability",
        "MilitarySpaceReadiness",
        "MilitarySpecialOperationsActivity",
        "MilitarySpecialOperationsCapability",
        "MilitarySpecialOperationsReadiness",
        "MilitarySpending",
        "MilitaryTraining",
        "MilitaryWMDActivity",
        "MiningIndustry",
        "NationalArmsProduction",
        "NationalInformation",
        "NonMilitaryInternalSecurityActivity",
        "NonMilitaryInternalSecurityCapability",
        "NonMilitaryInternalSecurityReadiness",
        "PeacekeepingActivity",
        "PetroleumIndustry",
        "Political",
        "PoliticalFrictionOrTension",
        "PoliticalOrganizations",
        "PopulaceEducationLevel",
        "PopulaceSupportForGovernment",
        "PopulaceSupportForMilitary",
        "PopulaceSupportForPolice",
        "PopulationGrowth",
        "PovertyRate",
        "PowerAvailability",
        "Production",
        "ProvisionOfAidOrSupport",
        "PublicFacilities",
        "Refugees",
        "Relations",
        "ReligiousSites",
        "ReligiousTensionsInGovt",
        "ReligiousTensionsInPopulation",
        "Sanctions",
        "SanitaryConditions",
        "SecurityForceAssistance",
        "SecuritySafetyLevel",
        "ServicesIndustry",
        "Social",
        "SocialCohesion",
        "StrategicCommunications",
        "Sustainment",
        "SustenanceManagement",
        "TerrorismFinancing",
        "TerroristActivities",
        "Transportation",
        "TransportationInfrastructure",
        "UnregulatedEconomy",
        "Utilities",
        "UtilitiesInfrastructure",
        "WasteServices",
        "WaterAvailability",
        "WaterTransportation",
        "WealthInequality",
        "WMDCapabilityPursuit"        
    ],
  'Relevance': [],
  'Normalizer': [
    "Longitudinal",
    "Simple",
    "Standard",
  ],
  'Units': [
    "%",
    "% of Electricity Output",
    "% of GDP",
    "% of General Govt Expenditures",
    "% of Merchandise Exports",
    "% of Population",
    "% of Total Employment",
    "Beds per 1,000 people",
    "Billion US$",
    "Cubic Meters",
    "Current US$",
    "Fraction of Populace",
    "Homicides per 100,000 People",
    "Index",
    "Index (0 = Most Corrupt; 100 = Least Corrupt)",
    "Index (0 = Most Free; 100 or Greater = Least Free)",
    "Kg. of Oil Equivalent per Capita",
    "Metric Tons",
    "Micrograms per Cubic Meter",
    "Million Passenger-Km",
    "Million Ton-Km",
    "Million US$",
    "Millon Ton-Km",
    "Mln passenger-km",
    "Mln tonne-km",
    "People",
    "Physicians per 1,000 people",
    "SIPRI Trend Indicator Value (Estimated Common Unit of Military Value)",
    "Sq. Km",
    "Toe per '000 USD",
    "Tractors",
    "Workers per 1,000 people",
    "[1=extremely underdeveloped to 7=well developed and efficient by international standards]",
    "kWh",
  ],
  'DocID': {},
}
