export const DEFAULT_TAGS = {
  'FactorClass': [
    "AgriculturalIndustry",
    "AirPollutionLevels",
    "AirTransportation",
    "AlternativeEnergyIndustry",
    "Corruption",
    "CriminalActivities",
    "EconomicProduction-GDP",
    "EducationAvailability",
    "EmploymentLevel",
    "FoodAndNutritionLevel",
    "ForeignArmsTrade",
    "ForeignInvestment",
    "FreedomOfExpression",
    "GovernmentAbilityToAddressBasicNeeds",
    "GovernmentEffectiveness",
    "GovernmentStability",
    "GovernmentTransparency",
    "GroundTransportation",
    "HealthcareAvailability",
    "InternationalTrade",
    "JudicialActivity",
    "ManufacturingIndustry",
    "MilitarySpending",
    "MiningIndustry",
    "PetroleumIndustry",
    "PopulaceEducationLevel",
    "PovertyRate",
    "PowerAvailability",
    "ProvisionOfAidOrSupport",
    "Refugees",
    "SanitaryConditions",
    "SecuritySafetyLevel",
    "ServicesIndustry",
    "TransportationInfrastructure",
    "UtilitiesInfrastructure",
    "WaterAvailability",
    "WaterTransportation",
    "WealthInequality",
  ],
  'Relevance': [
    '-1.0',
    '-0.5',
    '0.5',
    '0.75',
    '1.0',
  ],
  'Normalizer': [
    "Longitudinal",
    "Simple",
    "Standard",
  ],
  'Units': [
    "%",
    "% of Electricity Output",
    "% of GDP",
    "% of General Govt Expenditures",
    "% of Merchandise Exports",
    "% of Population",
    "% of Total Employment",
    "Beds per 1,000 people",
    "Billion US$",
    "Cubic Meters",
    "Current US$",
    "Fraction of Populace",
    "Homicides per 100,000 People",
    "Index",
    "Index (0 = Most Corrupt; 100 = Least Corrupt)",
    "Index (0 = Most Free; 100 or Greater = Least Free)",
    "Kg. of Oil Equivalent per Capita",
    "Metric Tons",
    "Micrograms per Cubic Meter",
    "Million Passenger-Km",
    "Million Ton-Km",
    "Million US$",
    "Millon Ton-Km",
    "Mln passenger-km",
    "Mln tonne-km",
    "People",
    "Physicians per 1,000 people",
    "SIPRI Trend Indicator Value (Estimated Common Unit of Military Value)",
    "Sq. Km",
    "Toe per '000 USD",
    "Tractors",
    "Workers per 1,000 people",
    "[1=extremely underdeveloped to 7=well developed and efficient by international standards]",
    "kWh",
  ],
  'DocID': {},
}
